### ISSUE TITLE
Allow other file types

### ISSUE THREAD

**Issue by aanton** [SudoKillMe/vscode-extensions-open-in-browser#11]
Hi!

It would be great if any file could be opened in the browser. In my personal case, i open markdown files in the browser (i use an extension to display them properly) and i would like to open them in the browser from vscode.

Regards

**Comment by john-cj** [comment]
@aanton For that reason, I use [open-in-browser](https://github.com/coderfe/vscode-open-in-browser) by coderfee. But, it doesn't have neat GUI button as TechER's extension. (I mean, when you click somewhere in the document with right mouse button and see "Open in browser" in context menu).
