### ISSUE TITLE
Open in Other Browsers isn't working?

### ISSUE THREAD

**Issue by spacesuitdiver** [SudoKillMe/vscode-extensions-open-in-browser#12]
I'm on OSX and am getting these errors, default works fine. *EDIT* this seems only broken in the command palette, the right click menu works.

![image](https://user-images.githubusercontent.com/2807897/36800341-ea0ee6a0-1c74-11e8-8f5e-2a83ef741b48.png)

**Comment by Eugenii10** [comment]
I also have these errors on Windows 10. Hotkeys and context menu work as intended, but if I try to run commands through the command palette (F1), I get these errors.

**Comment by Rushan-Chen** [comment]
![snip20180526_4](https://user-images.githubusercontent.com/20920726/40574078-c5be79cc-60fe-11e8-92c9-4fb6f03e673c.png)
I'm also getting this error on Mac OSX 10.13.

**Comment by Code6666** [comment]
I'm  win10  user   when  I  use  open-in-other-browser  function, it's  show me  the error that windows  can't  find the  file  'chrome'  ,please confirm the  file name  and  try again.

**Comment by Code6666** [comment]
![f6q8k d 706m32 5n5hbnk](https://user-images.githubusercontent.com/26238887/49624715-86547180-fa0d-11e8-83c7-68c53c29029b.png)
