### ISSUE TITLE
when opening with chrome, execute parallels's chrome 

### ISSUE THREAD

**Issue by chan48** [SudoKillMe/vscode-extensions-open-in-browser#2]
hi, first of all, thanks for this extensions. 

I'm mac user. whenever opening with chrome as default, execute parallels's chrome. 
Can you tell me how to fix this  & when you add opera browser?

**Comment by SudoKillMe** [comment]
@chan48 I do not understand what's the meaning of 'execute parallels's chrome', can you elaborate it ?
If somebody really needs opera browser, I will add it next version.
