### ISSUE TITLE
Running the contributed command:'extension.openInSpecifyBrowser' failed.

### ISSUE THREAD

**Issue by AlexanderFilatov** [SudoKillMe/vscode-extensions-open-in-browser#21]
Hello, friends!I have a problem with open combination!I make default combination!In begin all works, but now works only alt + B.(default browser chrome)In call context menu all works fine.I can select between browsers!My systems lubuntu 17.10.1 and visual studio code 1.24.1.
Sorry for my English!

**Comment by kelsonthony** [comment]
I have the same problem but with firefox + win10.

**Comment by wanghui47** [comment]
I have the same problem but with Chrome + win10.

**Comment by 1valdis** [comment]
Same. Win 8.1 + Chrome. How to fix this?

**Comment by krab7191** [comment]
Same issue, Ubuntu 16.04 LTS and Chrome.

**Comment by Ivankali2020** [comment]
same issue , ubuntu 20 LTS and Chrome
