### ISSUE TITLE
Open browser failed!! Please check if you have installed the browser FirefoxDeveloperEdition correctly!

### ISSUE THREAD

**Issue by SadWood** [SudoKillMe/vscode-extensions-open-in-browser#35]
Open browser failed!! Please check if you have installed the browser FirefoxDeveloperEdition correctly!
I can't open Firefox development on  Mac and I have reinstalled Firefox.

**Comment by core37** [comment]
I have the same problem. Have you solve this problem?

**Comment by SadWood** [comment]
> I have the same problem. Have you solve this problem?

I can't

**Comment by massimo-cassandro** [comment]
same problem

**Comment by Luich2012** [comment]
same problem
