### ISSUE TITLE
Can you add a config option to set browser starting parameters ?

### ISSUE THREAD

**Issue by mx601595686** [SudoKillMe/vscode-extensions-open-in-browser#4]
I realy hope there is a option to allow user to config a starting parameter. This is very useful when you want to change browser behavior. For example, when i am deveploing front-end project, i offen need browser allowing across domain, so i need passing ` --disable-web-security --user-data-dir=C:\MyChromeDevUserData` to enable this function.

**Comment by SudoKillMe** [comment]
@mx601595686  yeah, in fact I thought about that, but i don't thing this is **very useful**, I prefer to use a command in terminal...
of course, I will consider that and maybe add this next version
