### ISSUE TITLE
Open browser failed!

### ISSUE THREAD

**Issue by XurryAli** [SudoKillMe/vscode-extensions-open-in-browser#43]
![image](https://user-images.githubusercontent.com/24306789/52999296-59d2c200-3460-11e9-9b0e-ec253f60a528.png)

How to solve this problem？

**Comment by shamimgeek** [comment]
set default browser setting as below in user setting
```
"open-in-browser.default": "chrome"
```

**Comment by Manikanta-MK** [comment]
![error](https://user-images.githubusercontent.com/51439310/62755146-72777880-ba90-11e9-8ee5-decf402a23b2.JPG)
please solve this and where to change settings

**Comment by SudoKillMe** [comment]
I need more information @Manikanta-MK
