### ISSUE TITLE
Fix for Mac with Parallels

### ISSUE THREAD

**Issue by ngurney** [SudoKillMe/vscode-extensions-open-in-browser#7]
When I attempt to open a file with my default browser, it attempts to launch Chrome on my VM, Parallels, instead of on my Mac. 

If it helps, I am running Parallels 12.

**Comment by SudoKillMe** [comment]
Your description is not very clear, I guess you are working on VM, so your current working environment is VM and your default browser is the browser in your VM. Maybe you want to open browser in your mac while your working environment is VM, but I think this is imposible.

**Comment by ngurney** [comment]
@SudoKillMe sorry for my unclear description.

I am running VSCode on my MacOS, with my VM powered down. When I select open in browser in VSCode, it launches my VM and opens my file in Chrome on my Windows VM. It is as if the settings for Open-In-Browser are defaulted for Windows Google Chrome as opposed to MacOS Google Chrome. 

I would just like it to open the file in my MacOS Chome when I select the option to open in browser.

It opens fine in Firefox and Safari, as I don't have those applications on my Windows VM.

See this GIF: (https://cl.ly/0u3I3v3x2H2o)

**Comment by SudoKillMe** [comment]
@ngurney maybe I know why， I will test and try to fix it. Thanks for your feedback ! :)

**Comment by ngurney** [comment]
Thank you for such quick response! :)

**Comment by ngurney** [comment]
Just tested this and it seems to have been resolved. 

Cheers!
