### ISSUE TITLE
need docs

### ISSUE THREAD

**Issue by ghost** [SudoKillMe/vscode-extensions-open-in-browser#8]
I need to see a document that explains how to actually use_ the extension.

**Comment by hwaldstein** [comment]
Seconded. I need this too.

**Comment by Kiolali** [comment]
I have the same problem

**Comment by DavidRGriswold** [comment]
press alt-B (default browser) or alt-shift-b (to choose a browser) when in an HTML file. Or, right-click on the body of the editor. Or, right click on the file in the file explorer sidebar. Or (if my new pull request is accepted), right-click on the HTML files's title in the tab bar.
