### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by neilw73** [SudoKillMe/vscode-extensions-open-in-browser#9]
Hello,
Intellisense is working so I know it's installed. I enter into my user settings:

    "open-in-browser.default": ["firefox"]

and it still opens in Chrome.

I also tried

    "open-in-browser.default": "firefox"

and also IE.

Am I doing something wrong?

**Comment by SudoKillMe** [comment]
first, please let me know your os
second, please **make sure you have installed these browsers**
If there's still a problem, I will test it. 
@neilw73
